# Generated by Django 6.0 on 2026-01-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новости')], default='AR', max_length=7),
        ),
    ]
